name: Build Tasker

# Todo: Add matrix for build config and platform

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          vsversion: 18

      - name: Configure with CMake (Visual Studio 18 2026)
        run: |
          cmake -S . -B build `
            -G "Visual Studio 18 2026" `
            -A x64 `
            -DTSKR_BUILD_EXAMPLES_ALL=1

      - name: Build (Windows)
        run: cmake --build build --config Release

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Checkout repository
        uses: actions/checkout@v4
              
      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v2
        with:
          version: 16

      - name: Install dependencies
        run: |
          sudo apt-get install -y build-essential cmake ninja-build

      - name: Configure (Linux)
        run: |
          cmake -S . -B build \
            -G Ninja \
            -DTSKR_BUILD_EXAMPLES_ALL=1

      - name: Build (Linux)
        run: cmake --build build --config Release
  
  build-wasm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Setup emscripten
        uses: emscripten-core/setup-emsdk@v15

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get install -y build-essential cmake

      - name: build-wasm
        run: emcmake cmake . -B build/wasm

      - name: compile-wasm
        run: |
          cmake --build build/wasm --target clean
          cmake --build build/wasm
          mkdir bin
          mkdir bin/wasm
          emcc -g build/wasm/libbt_types.a -o bin/wasm/types.js

      